version: "3"
services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: social_network
      POSTGRES_DB: social_network
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/posgresql/data
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./social_network:/social_network
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: